version: '3.8'

services:
  storefront:
    # This pulls your automatically built image from Docker Hub
    image: pranith023/vito-ginglies:latest
    container_name: vito_storefront
    ports:
      # Maps your laptop's port 3000 to the container's unprivileged Nginx port 8080
      - "3000:8080"
    # This tells Docker to securely inject the keys from your hidden file
    env_file:
      - .env
    restart: unless-stopped